[32mINFO    [0m root:test_03_message.py:289 请求成功